#! /bin/bash
set -e

export LD_LIBRARY_PATH=./src/util
export DYLD_FALLBACK_LIBRARY_PATH=./src/util
cargo +nightly run $@
# cargo build $@
# PID=$(pidof rust-recipes)
# echo "Running under pid: $$"
# exec ./target/debug/rust-recipes

