#! /bin/bash
set -e

cargo build -p=dynamic_library --lib
(cd dynamic_library/src && make call_rust)
LD_LIBRARY_PATH=./target/debug DYLD_FALLBACK_LIBRARY_PATH=./target/debug ./dynamic_library/src/call_rust
