#! /bin/bash

LD_LIBRARY_PATH=./src/util
rm ./src/util/libmylib.so
cargo build --target aarch64-unknown-linux-musl
file ./src/util/libmylib.so
file ./target/aarch64-unknown-linux-musl/debug/rust-recipes
